#GCP App Engine config YAML
#ref: https://cloud.google.com/appengine/docs/standard/reference/app-yaml?tab=node.js

runtime: nodejs18
handlers:
  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$
  - url: /.*
    static_files: build/index.html
    upload: build/index.html